### PR TITLE
Suggestions from Joel's review

### PR DESCRIPTION
**Pull request by joelostblom**
I didn't go through it in super detail, but here are some suggestions. I tried to keep the commits atomic so that you can take and leave what you want. Descriptions for most suggestions are in the commit message, but I will go ahead and leave some specific line comments as well.

### CODE REVIEW

**Comment by joelostblom** [comment]
Sigh , the file is too large to leave line comments so I'll do it with screens here instead. @ttimbers ready for review:

> `SSLError: HTTPSConnectionPool(host='archive.ics.uci.edu', port=443): Max retries exceeded with url: /static/public/15/breast+cancer+wisconsin+original.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)')))`

I ran into this error when reading the data and had to set `verify=False` which is not recommended. Not sure if it could be on my end but looks like their cert expired?

> image

I think this model performance is great and could have clinical utility as a screening tool. I made the importance of the context more explicit.

> image

 The resolved on the axis will happen autoamtically when the scale is resolved (but not the other way around). I think we want to share the x-axis here since all features are normalized to a similar range, no? I made it 5 columns so that the rows are divded by max,mean,sd and the grid is square.

> image

Further down you were computing sem from sd by dividing by 10, but I think it should be 30 since we had 30 folds. I'm guessing it was maybe changed from 10 to 30 and not updated in both places, so this will avoid issues if it is changed again.

> image

I think it is cleaner to do this in one chain and could be a nice opportunity for them to learn about `lambda` in chained assignments if they don't already know it. I would actually vote for always using `lambda` with assign, even in the first example that I didn't change in this PR. When we use assign with the original name of the dataframe it only works when we don't do any updates to the column in the same chain. However, this caveat is not intuitive I think it is likely we are setting students up for unintended side effects from the calls to assign by using the name of the df instead of `lambda`.

> image

This is more similar to how I taught things in 531 and avoids the use of a dict to set color of points

> image

I don't think setting `average='weighted'` here leads to the desired result. My understand is that it will compute the F2 score for both 'Benign' and 'Malignant' and then take the weighted average of those. But we specifically want 'Malignant' as our positive label since False Negatives are more damaging. Pinging @kvarada who can confirm.

On the same topic, should we call it F2 score (at least in the text) instead of Fbeta score (the same way we call it F1 score)? Both might be technically correct, but I am not sure if one is more common. 

> image

This is what we did in 573. Nothing wrong with crosstab though, I should probably include that in 573 as well instead of the sklearn function to get the numbers. Just thought I would give a headsup and you can pick.

**Comment by ttimbers** [comment]
Thank-you for these great suggestions @joelostblom ! I will incorporate them all. 

As for the naming of the F2 score in the narrative here, Fbeta - that is because I was following your 573 notes (see screenshot below). Fbeta is referred to 5 times in the document, including in the explanation, and F2 is only referred to once in the code.

Screenshot 2023-11-14 at 10 02 59 AM

**Comment by joelostblom** [comment]
Ah yes, I should probably add a sentence there mentioning that we call it F2 score when beta=2. The five references to `fbeta` in the document are just for the function name in the code, so that won't change regardless of what we call it in the text.

**Comment by ttimbers** [comment]
I think that I am going to stick with `crosstab` instead of `ConfusionMatrixDisplay`. The confusion matrix is quite simple here, and I think that the extra bells and whistles are not needed, and possibly distracting. I think if there were more classes, with a range of values, this would be quite useful.

**Comment by ttimbers** [comment]
Also, I don't have this error:

> `SSLError: HTTPSConnectionPool(host='archive.ics.uci.edu', port=443): Max retries exceeded with url: /static/public/15/breast+cancer+wisconsin+original.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)')))`

I am not sure why things are differing for us... I am on mac and running in the conda env with this project and in VSCode.

**Pull request merged**
